POST https://10.120.32.74/web-page/api/v1/users
Content-Type: application/json

{
  "name": "Tony",
  "username": "test",
  "password": "qwe123",
  "email": "tonykar@example.com"
}

### Post login
POST https://10.120.32.74/web-page/api/v1/auth/login
content-type: application/json

{
  "username": "bobiii",
  "password": "qwe123"
}

### Get my user info
GET https://10.120.32.74/web-page/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2MywibmFtZSI6IlRvbnkiLCJ1c2VybmFtZSI6ImJvYmkiLCJlbWFpbCI6InRvbnlrYXJAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTMxMDM5OSwiZXhwIjoxNzQ1Mzk2Nzk5fQ.gqhohThxR8Fk49nuhYu_xl-Q_i40ot06raWH20gM4Bw


### Get users
GET https://10.120.32.74/web-page/api/v1/users

### PUT users
PUT https://10.120.32.74/web-page/api/v1/users
content-type: application/json

{
  "username": "tonykar",
  "password": "12345"
}

### Update username
PUT https://10.120.32.74/web-page/api/v1/users/63
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo2MywibmFtZSI6IlRvbnkiLCJ1c2VybmFtZSI6ImJvYmlpaSIsImVtYWlsIjoidG9ueWthckBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQ1MzE3NDEyLCJleHAiOjE3NDU0MDM4MTJ9.7QTnOan6W_ZY6Mx1sPKeQy9wBiQTum6dE6pcfDrR3fs

{
  "username": "testbob",
  "currentPassword": "qwe123",
  "newPassword": "asd123"
}

### Delete user account
DELETE https://10.120.32.74/web-page/api/v1/users/54
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1NCwibmFtZSI6InRvbnkiLCJ1c2VybmFtZSI6ImJvYmkiLCJlbWFpbCI6ImJvYmlAdGVzdC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTI3NTY3NywiZXhwIjoxNzQ1MzYyMDc3fQ.hJmZ_882YZl-oHFC7z3gccM6jyYFTjoR1Scn7hKGkYQ


